[package]
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]
name = "giti"
version = "0.2.4"

[dependencies]
git2 = "0.7.0"
self_update = "0.4.2"
term = "0.5.1"
hubcaps = "0.4.5"
tokio-core = "0.1.17"
hyper = "0.11.25"
hyper-tls = "0.1.2"
futures = "0.1.0"
futures-await = "0.1"
